services:
  - type: web
    name: goat-pedigree
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn goat_pedigree.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: postgres://<username>:<password>@<host>:<port>/<database>