# Generated by Django 5.1.5 on 2025-02-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goat',
            name='age',
        ),
        migrations.AddField(
            model_name='goat',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_children', to='goats.goat'),
        ),
        migrations.AddField(
            model_name='goat',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered_children', to='goats.goat'),
        ),
        migrations.AddField(
            model_name='goat',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
