# Generated by Django 5.1.5 on 2025-02-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0002_remove_goat_age_goat_birth_date_goat_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goats/'),
        ),
    ]
