# Generated by Django 5.1.5 on 2025-03-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0005_alter_goat_father_alter_goat_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_children', to='goats.goat'),
        ),
        migrations.AlterField(
            model_name='goat',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goat',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_children', to='goats.goat'),
        ),
        migrations.AlterField(
            model_name='goat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goat',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
