# Generated by Django 4.2.20 on 2025-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0006_alter_goat_father_alter_goat_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload an image of the goat with a clear view of the face. Use the goat's name in .jpg format, e.g., lucy.jpg", null=True, upload_to='goats/'),
        ),
    ]
