# Generated by Django 5.2.10 on 2026-01-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0007_alter_goat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='species',
            field=models.CharField(choices=[('goat', 'Goat'), ('sheep', 'Sheep')], default='goat', max_length=10),
        ),
    ]
