# Generated by Django 4.2 on 2026-01-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0008_goat_species'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('goats', 'Goat').objects.filter(species__in=['', None]).update(species='goat'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
