# Generated by Django 5.1.5 on 2025-01-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
